name: Build Vue
on: 
  push:
    branches: [main, config/gh-actions]
  pull_request:
    branches: [main]


jobs:
  build_vue:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: torch-front
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - run: npm run build
  GHPdeploy:
    runs-on: ubuntu-latest
    name: Deploy to branch
    steps:
    - run: git config --global user.email "eric.durr.20@ull.edu.es"
    - run: git config --global user.name "eric.durr.20@ull.edu.es"
    - run: git add torch-front/dist -f && git commit -m 'adding dist subtree'
    - run: git subtree push --prefix torch-front/dist origin gh-pages