name: Build Vue
on: 
  push:
    branches: [main, config/gh-actions]
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: torch-front

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - run: npm install
    - run: npm run build
    - run: git config --global user.email "eric.durr.20@ull.edu.es"
    - run: git config --global user.name "Eric-Durr"
    - run: git add dist -f && git commit -m 'adding dist subtree'
    - run: git subtree push --prefix dist origin gh-pages