name: Build Vue
on: 
  push:
    branches: [main, config/gh-actions]
  pull_request:
    branches: [main]
default:
  runs:
    working-directory: torch-front

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - run: npm run build
    - run: git add dist && git commit -m 'adding dist subtree'
    - run: git subtree push --prefix dist origin gh-pages