name: Build Vue
on: 
  push:
    branches: [main, config/gh-actions]
  pull_request:
    branches: [main]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        working-directory: torch-front
        username: 'Eric-Durr'
        reponame: '/SyTW-2122/E02/'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged