name: Deploy
on: 
  push:
    branches: [main, config/gh-actions]
  pull_request:
    branches: [main]

jobs:
  deploy-front:
    name: Deploy frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: git remote add heroku-front https://git.heroku.com/torch-interface.git
      - run: git push --force heroku-front `git subtree split --prefix torch-front HEAD`:main