name: Deploy
on: 
  push:
    branches: [main, config/gh-actions]
  pull_request:
    branches: [main]
jobs:
  deploy-back:
    name: Deploy backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
      - run: git push --force heroku `git subtree split --prefix torch-back HEAD`:main
        if: always()
      - uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }} # required
          notify_when: 'failure'
          notification_title: '{workflow} has {status_message}'
          message_format: '{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>'
          footer: 'Linked to Repo <{repo_url}|{repo}>'
          notify_when: 'failure'
          #mention_users: 'U0160UUNH8S,U0080UUAA9N'
          #mention_users_when: 'failure,warnings'
          #mention_groups: 'SAZ94GDB8'0
          #mention_groups_when: 'failure,warnings'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}