name: Frontend actions for CI/CD
on:
  push:
    branches: [ main ]

defaults:
  run:
    working-directory: torch-front

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - uses: cypress-io/github-action@v2.2.7
        with:
          install: false
          start: npm run test:ci
          wait-on: http://localhost:3000
  #build:
  #deploy: