name: Frontend actions for CI/CD
on:
  push:
    branches: [ main, config/gh-actions ]
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: torch-front

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run test:unit
        if: always()
      - uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }} # required
          notify_when: 'failure,warnings'
          notification_title: '{workflow} has {status_message}'
          message_format: '{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>'
          footer: 'Linked to Repo <{repo_url}|{repo}>'
          mention_users: 'Alejando Martín de León'
          mention_users_when: 'failure,warnings'
          #mention_groups: 'SAZ94GDB8'0
          #mention_groups_when: 'failure,warnings'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}   
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run serve &
      - run: npm run test:ci
        if: always()
      - uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }} # required
          notify_when: 'failure,warnings'
          notification_title: '{workflow} has {status_message}'
          message_format: '{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>'
          footer: 'Linked to Repo <{repo_url}|{repo}>'
          mention_users: 'Alejando Martín de León'
          mention_users_when: 'failure,warnings'
          #mention_groups: 'SAZ94GDB8'0
          #mention_groups_when: 'failure,warnings'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}   