name: Frontend actions for CI/CD
on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: Enter frontend folder
        - run: cd torch-front

        - name: Install dependencies
        - run: npm install

        - name: Run tests
        - run: npm test