name: Backend actions for CI/CD
on:
  push:
    branches: [ main ]

defaults:
  run:
    working-directory: torch-front

jobs:
  test:
    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - run: cd torch-back
      - run: npm install
      - run: npm run test
  #build:
  #deploy: