name: Frontend actions for CI/CD
on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Enter frontend folder
      - run: cd torch-front

      - name: Install dependencies
      - run: npm install

      - name: Run tests
      - run: npm test

  #build:
  #deploy: