name: Backend actions for CI/CD
on:
  push:
    branches: [ main ]

defaults:
  run:
    working-directory: torch-back

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run test
  #build:
  #deploy: