name: Backend actions for CI/CD
on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Enter backend folder
      - run: cd torch-back

      - name: Install dependencies
      - run: npm install
      - run: npm run test
  #build:
  #deploy: